.gitignore
app/Home.module.css
app/components/App.module.css
app/components/App.tsx
app/components/OvVideo.tsx
app/components/UserVideoComponent.tsx
app/main/page.tsx
next.config.mjs
package-lock.json
package.json
tsconfig.json

Feat: videochat

---

app/components/App.tsx

fix: leave session

---

app/components/App.tsx
app/main/page.tsx
app/waiting/page.tsx

waiting 화면에서 세션 접속, main화면에서 화상 송출

#6 feat : waiting 화면에서 main으로 접속 설정

---

.gitignore
app/components/STTComponent.tsx

추후 main server 미들웨어 주소로 변경해야함 현재는 바로 nlp 에 접속하지만 main으로 접속해서 main에서 키워드 추출 요청을 보내도록 수정할것.

refactor: nlp_server url 을 환경변수에서 가져오도록 변경

---

app/components/App.tsx
app/components/NetworkGraph.tsx
app/components/NodeList.tsx
app/components/STTComponent.tsx
app/main/page.tsx
app/stt/page.tsx

Feat:transcript print

---

.gitignore
app/components/NetworkGraph.tsx
app/components/STTComponent.tsx

텍스트로 변환된 음성을 키워드로 추출하여 노드 생성 완료

---

app/components/STTComponent.tsx
app/waiting/page.tsx

- 오픈비두 및 키워드 추출 기능 메인 서버 api 요청으로 전환

#12 feat: main server connect

---

app/api/auth/[...nextauth]/route.ts
app/utils/authOptions.ts

- npm run build 시 auth 파일 에러 수정

fix: deployment error

---

app/page.tsx

fix: deployment

---

app/components/NetworkGraph.tsx
app/hooks/useNetwork.ts

#19 fix : 노드 생성시 라벨에 따라 크기가 변경되는 이슈 해결

---

app/components/NetworkGraph.tsx
app/hooks/useNetwork.ts

- 부분 랜더링으로 노드 상태 변경시 그래프 뷰가 랜더링 되는 상황 수정
- 상태관리 훅 수정하여 노드 활성화/비활성화 상태관리 최적화

메인페이지 노드 뷰 버그 수정

---

app/components/NetworkGraph.tsx
app/main/page.tsx

#24 #25 #31 feat: keyword 생성 기능 추가

---

app/Home.module.css
app/components/Conversation.tsx
app/components/NetworkGraph.tsx
app/components/NodeCoversation.tsx

키워드, 대화내용 탭 

---

.gitignore
app/components/STTComponent.tsx
app/lib/socket.ts
app/waiting/page.tsx
next.config.mjs
package-lock.json
package.json

.env.local
.env.production 
환경 값을 가지고 로컬 main-server, 배포 main-server 
url 값이 바뀜.
```
npm run start:local
```
```npm run start:prod
```

로컬, 배포 env 에 따라 run 가능하도록 기능 추가.

---

app/components/NetworkGraph.tsx

#35 fix : 메인페이지 레이아웃 조정

---

app/components/NetworkGraph.tsx
app/components/SocketProvider.tsx
app/components/sharingRoom.tsx
app/main/page.tsx
app/waiting/page.tsx

#43 feat: 방 링크 공유 버튼 생성

---

app/Home.module.css
app/components/GroupedNodeList.tsx
app/components/NetworkGraph.tsx
app/components/NodeConversation.tsx

메인페이지 UI개선중

---

app/Home.module.css
app/components/ControlPanel.tsx
app/components/Conversation.tsx
app/components/GroupedNodeList.tsx
app/components/NetworkGraph.tsx
app/components/NodeConversation.tsx
app/components/NodeList.tsx
app/components/VoiceRecorder/VoiceRecorder.tsx

- 컨트롤 패널 하단바로 분리
- 노드그래프 양옆 탭 UI개선

메인페이지 UI수정

---

app/components/Network/NetworkGraph.tsx
app/hooks/useNetwork.ts
app/main/page.tsx

#52 refactor : 컨트롤 패널 분리

---

app/_components/Video/Video.module.css
app/_components/Video/Video.tsx
app/main/Main.module.css
app/main/page.tsx

비디오 UI수정 중

---

app/main/page.tsx

voiceRecorder 하단바로

---

app/_components/Network/NetworkGraph.tsx
app/_components/Network/styles/NetworkGraph.module.css
app/_hooks/useNetwork.ts
app/_types/types.ts

feat : 노드 머리위에 툴팁으로 컨텐트 보이기

---

app/_components/Network/styles/NodeConversation.module.css
app/_components/Network/styles/NodeList.module.css
app/_components/Video/Video.module.css
app/_components/Video/Video.tsx
app/_components/meetingRoom/MeetingRoom.module.css
app/_components/meetingRoom/MeetingRoom.tsx
app/meetingRoom/page.tsx
app/styles/Footer.module.css
app/styles/Header.module.css

메인페이지 UI개선

---

app/_types/types.ts
app/result/page.tsx

결과 페이지에 대화내역 그려짐

---

app/result/Result.module.css
app/result/page.tsx

result 컨텐츠 css 수정

---

app/_components/meetingRoom/MeetingRoom.module.css
app/_components/meetingRoom/MeetingRoom.tsx
app/_components/sharingRoom.tsx

컨트롤 패널 UI수정중

---

app/_components/Network/styles/NetworkGraph.module.css
app/_components/VoiceRecorder/SettingSlider.tsx
app/_components/VoiceRecorder/VoiceRecorder.tsx
app/_components/meetingRoom/MeetingRoom.module.css
app/_components/meetingRoom/MeetingRoom.tsx
app/styles/SettingsSlider.module.css

voiceRecorder ui개선

---

app/_components/meetingRoom/MeetingRoom.module.css
app/_components/meetingRoom/MeetingRoom.tsx
app/styles/SettingsSlider.module.css

컨트롤패널 UI 개선

---

app/_components/Video/UserVideoComponent.tsx
app/result/page.tsx

#83 feat: 결과 페이지 구현

---

app/_components/AudioPlayer.tsx
app/_types/types.ts
app/result/page.tsx
app/styles/AudioPlayer.module.css

결과 페이지 오디오 관련 구현 1차 완료

---

app/_components/VoiceRecorder/VoiceRecorder.tsx

recording timestamp를 서버에 송신하는 것을 메인 브랜치에 병합

---

app/result/Result.module.css
app/result/page.tsx

음성기록 UI수정 및 타임 스탬프 로컬 타임으로

---

app/_components/Network/NetworkGraph.tsx
app/_hooks/useNetwork.ts
app/result/page.tsx

탭 전환시 그래프가 제대로 렌더링

---

app/_components/AudioPlayer.tsx
app/result/Result.module.css
app/result/page.tsx

feat : 음성파일 재생시 음성기록에서 자동으로 타임스탬프를 따라감

feat : 음성파일 재생시 음성기록에서 자동으로 타임스탬프를 따라감

---

app/_components/AudioPlayer.tsx
app/result/Result.module.css
app/result/page.tsx
app/styles/AudioPlayer.module.css
app/styles/Footer.module.css

커스텀 오디오 플레이어 구현

---

app/_components/VoiceRecorder/VoiceRecorder.tsx

blob 그대로 stt 요청을 메인 브랜치에 병합

---

app/_components/Network/Conversation.tsx
app/_components/Network/NodeConversation.tsx
app/_components/Network/NodeList.tsx
app/_hooks/useHomeContent.ts

방 공유 기능 수정 및 키워드 요약 tailwind로

---

app/_components/VoiceRecorder/VoiceRecorder.tsx
app/_components/meetingRoom/MeetingRoom.tsx

#77 Design : 메인페이지 UI개선

---

app/_components/meetingRoom/MeetingRoom.tsx

Design : 노드컨버세이션, 보이스레코더 UI개선

---

app/board/page.tsx
app/result/page.tsx

- 결과화면에 회의록 정보 받아오기 
- 게시판 기본 기능 구현 완료

결과화면 데이터 출력 및 게시판 기본 기능 생성

---

app/board/page.tsx

게시판에서 회의록 삭제, 페이징, 날짜별 오름차순 내림차순 기능 구현

---

app/result/page.tsx

게시판 에러처리 수정

---

app/result/page.tsx
package-lock.json
package.json

feat : 결과화면 회의록 초안 완성

---

app/board/page.tsx

오름차순 상태관리 개선 및 title을 사용해 회의록 찾기, 페이지 UI개선

오름차순 상태관리 개선 및 title을 사용해 회의록 찾기, 페이지 UI개선

---

app/_components/AudioPlayer.tsx
app/_components/Video/Video.tsx
app/board/page.tsx
app/result/page.tsx

refactor: get 요청을 SSE로 변경

---

app/_components/Video/Video.module.css
app/_components/common/Header.tsx
app/_components/meetingRoom/MeetingRoom.tsx

헤더 수정 및 메인페이지 UI개선

---

app/_components/Network/NodeConversation.tsx
app/_components/Network/NodeList.tsx
app/_components/common/Header.tsx
app/_components/meetingRoom/MeetingRoom.tsx
app/meetingRoom/page.tsx

노드클릭시 그룹 펼쳐서 해당 노드로, 새로운 대화 기록이 쌓이면 자동으로..

 feat : nodeConversation 컴포넌트 자동 스크롤 기능 추가

---

app/_components/Socket/SocketContext.tsx
app/_components/Video/Video.tsx

서버로부터 소켓 끊길때마다 openvidu 세션 연결 문제을 메인 브랜치에 병합

---

app/_components/Network/ControlPanel.tsx
app/_components/meetingRoom/MeetingRoom.module.css

fix : 밀리는 현상 수정

---

app/result/page.tsx

결과화면 탭 순서 변경

---

app/_components/VoiceRecorder/VoiceRecorder.tsx

어셈블리어로 eq작업 롤백을 메인 브랜치에 병합

---

app/_components/Network/NodeConversation.tsx
app/_components/VoiceRecorder/VoiceRecorder.module.css
app/_components/VoiceRecorder/VoiceRecorder.tsx
app/_components/common/Header.tsx
app/_components/meetingRoom/MeetingRoom.tsx
app/styles/SettingsSlider.module.css

Design : 보이스레코더 사이즈 축소 및 노드컨버세이션 크기 키움

---

app/_components/VoiceRecorder/VoiceRecorder.tsx
app/_components/meetingRoom/MeetingRoom.tsx
app/styles/SettingsSlider.module.css

Design : 보이스레코더 수정

---

app/_components/meetingRoom/MeetingRoom.tsx
app/styles/SettingsSlider.module.css

fix : 비디오 스크롤 불가능 이슈 해결

---

app/_components/Network/NodeConversation.tsx
app/_hooks/useSocketHandlers.ts

배치 단위로 처리 및 큐를 사용해 데이터를 순차적으로 처리을 메인 브랜치에 병합

---

app/result/page.tsx

mom 컬럼 변경 및 진행 시간 추가을 메인 브랜치에 병합

---

app/_components/Network/NodeList.tsx
app/_utils/unionFind.ts
package-lock.json
package.json

fix : 노드리스트 로직 수정 및 UI개선을 통해 최적화

---

app/_components/AudioPlayer.tsx
app/_components/Network/ControlPanel.tsx

- 미팅룸에서 connect / disconnect 상태 관리로 활성화/비활성화 모드 추가
- 오디오 플레이어 타임스탬프 클릭시 아이콘 안변하는 버그 수정

#162 fix : 버그 수정 및 UI개선
